server:
  port: ${REVIEW_SERVICE_PORT:8083}

spring:
  application:
    name: review-service
  
  datasource:
    url: ${REVIEW_DB_URL:jdbc:postgresql://20.214.91.15:5432/hiorder_review}
    username: ${REVIEW_DB_USERNAME:hiorder_user}
    password: ${REVIEW_DB_PASSWORD:hiorder_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

  azure:
    eventhub:
      connection-string: ${AZURE_EVENTHUB_CONNECTION_STRING}
      consumer-group: $Default

file-storage:
  base-path: ${FILE_STORAGE_PATH:/var/hiorder/uploads}
  allowed-extensions: jpg,jpeg,png,gif,webp
  max-file-size: 10485760  # 10MB

springdoc:
  api-docs:
    path: /docs/review/api-docs
  swagger-ui:
    enabled: true
    path: /docs/review/swagger-ui.html
